config/routes.rb
Residence::Application.routes.draw do

root :to => 'static_pages#home'
  resources :properties

  resources :users

  resources :messages

  get "static_pages/home"

  get "static_pages/aboutUs"

  get "static_pages/contactUs"

  get "static_pages/privacyPolicy"

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :date_read, :date_sent, :receiver_id, :sender_id, :subject
  
  
  belongs_to :user
  
  
validates :date_read, :presence => true
validates :date_sent, :presence => true
validates :receiver_id, :presence => true
validates :sender_id, :presence => true
validates :subject, :presence => true 

end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :internet_included, :manager_id, :number_of_bathrooms, :number_of_bedrooms, :number_of_rooms, :owner_id, :owner_name, :parking_allotment, :period_type, :price_per_period, :property_type, :purpose, :street_address
  
  
belongs_to :user

validates :manager_id, :presence => true
validates :owner_id, :presence => true
validates :owner_name, :presence => true
validates :property_type, :presence => true 
validates :period_type, :presence => true
validates :price_per_period, :presence => true


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :Admin, :contact_email, :contact_phone, :name
  
  before_save :format_phone
  
  has_many :messages
  has_many :properties
  
phone_regex = /^\+?\d{11}|\+?\d{3}[-.]\d{4}[-.]\d{4}$/

validates :contact_email, :presence => true
validates :name, :presence => true
validates :contact_phone, :presence => true, :format => { :with => phone_regex, :message => "should be 11 digits (country code needed) and delimited with dashes" }



private
	def format_phone
		phone=self.phone.to_s
		phone.gsub!(/[^0-9]/, "")
		self.phone=phone
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def aboutUs
  end

  def contactUs
  end

  def privacyPolicy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "ResidenceQatalogue"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="round"> 
    <ul id="footercss">
      <%= link_to "Home", static_pages_home_path %> :: 
      <%= link_to "About Us", static_pages_aboutUs_path %> :: 
      <%= link_to "Contact Us", static_pages_contactUs_path %></li> :: 
      <%= link_to "Privacy Policy", static_pages_privacyPolicy_path %> :: 
      <%= link_to "Webmaster", '#' %>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
	<%= yield %>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :date_sent %><br />
    <%= f.date_select :date_sent %>
  </div>
  <div class="field">
    <%= f.label :date_read %><br />
    <%= f.date_select :date_read %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :sender_id %><br />
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :receiver_id %><br />
    <%= f.number_field :receiver_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Date sent</th>
    <th>Date read</th>
    <th>Body</th>
    <th>Sender</th>
    <th>Receiver</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.subject %></td>
    <td><%= message.date_sent %></td>
    <td><%= message.date_read %></td>
    <td><%= message.body %></td>
    <td><%= message.sender_id %></td>
    <td><%= message.receiver_id %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @message.subject %>
</p>

<p>
  <b>Date sent:</b>
  <%= @message.date_sent %>
</p>

<p>
  <b>Date read:</b>
  <%= @message.date_read %>
</p>

<p>
  <b>Body:</b>
  <%= @message.body %>
</p>

<p>
  <b>Sender:</b>
  <%= @message.sender_id %>
</p>

<p>
  <b>Receiver:</b>
  <%= @message.receiver_id %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number_of_rooms %><br />
    <%= f.number_field :number_of_rooms %>
  </div>
  <div class="field">
    <%= f.label :number_of_bedrooms %><br />
    <%= f.number_field :number_of_bedrooms %>
  </div>
  <div class="field">
    <%= f.label :number_of_bathrooms %><br />
    <%= f.number_field :number_of_bathrooms %>
  </div>
  <div class="field">
    <%= f.label :parking_allotment %><br />
    <%= f.check_box :parking_allotment %>
  </div>
  <div class="field">
    <%= f.label :internet_included %><br />
    <%= f.check_box :internet_included %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :property_type %><br />
    <%= f.text_field :property_type %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br />
    <%= f.number_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :manager_id %><br />
    <%= f.number_field :manager_id %>
  </div>
  <div class="field">
    <%= f.label :price_per_period %><br />
    <%= f.number_field :price_per_period %>
  </div>
  <div class="field">
    <%= f.label :period_type %><br />
    <%= f.text_field :period_type %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br />
    <%= f.text_area :purpose %>
  </div>
  <div class="field">
    <%= f.label :owner_name %><br />
    <%= f.text_field :owner_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>Number of rooms</th>
    <th>Number of bedrooms</th>
    <th>Number of bathrooms</th>
    <th>Parking allotment</th>
    <th>Internet included</th>
    <th>Street address</th>
    <th>Property type</th>
    <th>Owner</th>
    <th>Manager</th>
    <th>Price per period</th>
    <th>Period type</th>
    <th>Purpose</th>
    <th>Owner name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.number_of_rooms %></td>
    <td><%= property.number_of_bedrooms %></td>
    <td><%= property.number_of_bathrooms %></td>
    <td><%= property.parking_allotment %></td>
    <td><%= property.internet_included %></td>
    <td><%= property.street_address %></td>
    <td><%= property.property_type %></td>
    <td><%= property.owner_id %></td>
    <td><%= property.manager_id %></td>
    <td><%= property.price_per_period %></td>
    <td><%= property.period_type %></td>
    <td><%= property.purpose %></td>
    <td><%= property.owner_name %></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', edit_property_path(property) %></td>
    <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number of rooms:</b>
  <%= @property.number_of_rooms %>
</p>

<p>
  <b>Number of bedrooms:</b>
  <%= @property.number_of_bedrooms %>
</p>

<p>
  <b>Number of bathrooms:</b>
  <%= @property.number_of_bathrooms %>
</p>

<p>
  <b>Parking allotment:</b>
  <%= @property.parking_allotment %>
</p>

<p>
  <b>Internet included:</b>
  <%= @property.internet_included %>
</p>

<p>
  <b>Street address:</b>
  <%= @property.street_address %>
</p>

<p>
  <b>Property type:</b>
  <%= @property.property_type %>
</p>

<p>
  <b>Owner:</b>
  <%= @property.owner_id %>
</p>

<p>
  <b>Manager:</b>
  <%= @property.manager_id %>
</p>

<p>
  <b>Price per period:</b>
  <%= @property.price_per_period %>
</p>

<p>
  <b>Period type:</b>
  <%= @property.period_type %>
</p>

<p>
  <b>Purpose:</b>
  <%= @property.purpose %>
</p>

<p>
  <b>Owner name:</b>
  <%= @property.owner_name %>
</p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/static_pages/aboutUs.html.erb
<% provide(:title, 'About us') %>
<!DOCTYPE html>
<html>
  <head>
    <title>Residence Qatalogue | <%= yield(:title) %></title>
  </head>
  <body>
    <h1>About us</h1>
	<p>The Ministry of Labor has (finally) decided to respond to the problem of finding a residence in Qatar, for both short term and long term visitors to the country. As such, it has commissioned you to create a Residence Qatalogue: a listing (that allows entry, editing and deletion) of residences in Doha. It should also allow users to sign in to accomplish these tasks and also send each other messages. Lastly, the system should allow the owner of a property to transfer ownership of a property, and to assign a manager.</p>
	
  </body>
</html>

app/views/static_pages/contactUs.html.erb
<% provide(:title, 'Contact us') %>
<h1>Contact Us</h1>

<p>Sara AlMulla<br/>
email:smulla@qatar.cmu.edu <br/>
Telephone:44674580
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
  <head>
    <title>ResidenceQatalogue | <%= yield(:title) %></title>
  </head>
  <body>
    <h1>Residence Catalogue</h1>
	<p>
	The Ministry of Labor has (finally) decided to respond to the problem of finding a residence in Qatar, for both short term and long term visitors to the country. As such, it has commissioned you to create a Residence Qatalogue: a listing (that allows entry, editing and deletion) of residences in Doha. It should also allow users to sign in to accomplish these tasks and also send each other messages. Lastly, the system should allow the owner of a property to transfer ownership of a property, and to assign a manager. 
	</p>
  </body>
</html>

app/views/static_pages/privacyPolicy.html.erb
<% provide(:title, 'Privacy policy') %>
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  </head>
<body>
    <h1>Privacy Policy</h1>
	<p></p>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br />
    <%= f.number_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :Admin %><br />
    <%= f.check_box :Admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Contact email</th>
    <th>Contact phone</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.contact_email %></td>
    <td><%= user.contact_phone %></td>
    <td><%= user.Admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Contact email:</b>
  <%= @user.contact_email %>
</p>

<p>
  <b>Contact phone:</b>
  <%= @user.contact_phone %>
</p>

<p>
  <b>Admin:</b>
  <%= @user.Admin %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>